Description: >
  Template for creating S3 bucket and DynamoDB table to hold Terraform state and locks.
  Example Usage:
  Validate: aws cloudformation validate-template --template-body file://terraform-state-s3-backend.yml --region us-east-1
  Deploy: aws cloudformation create-stack --region us-east-1 --stack-name Terraform-State-Backend-Resources --enable-termination-protection --template-body file://terraform-state-s3-backend.yml
  Optionally add: --parameters ParameterKey=TerraformStateBucketName,ParameterValue=terraform-state-backend-jyylab ParameterKey=TerraformStateLockTableName,ParameterValue=terraform-state-locks

Parameters:
  TerraformStateBucketName:
    Type: String
    Default: terraform-state-backend-jyylab
    Description: The name of the S3 bucket to store Terraform state files. Make sure the bucket name is unique.
  TerraformStateLockTableName:
    Type: String
    Default: terraform-state-locks
    Description: The name of the DynamoDB table to store Terraform state locks.

Resources:
  S3BucketTerraformStateBackend:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::S3::Bucket"
    DeletionPolicy: "Retain"
    Properties:
      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        BlockPublicAcls: true
      BucketName: !Ref TerraformStateBucketName
      VersioningConfiguration:
        Status: "Enabled"
      OwnershipControls:
        Rules:
        - ObjectOwnership: "BucketOwnerEnforced"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - BucketKeyEnabled: true
          ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
      Tags:
      - Value: "terraform_states"
        Key: "terraform_s3_backend"
  DynamoDBTableTerraformLocks:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::DynamoDB::Table"
    DeletionPolicy: "Retain"
    Properties:
      SSESpecification:
        SSEEnabled: false
      TableName: !Ref TerraformStateLockTableName
      AttributeDefinitions:
      - AttributeType: "S"
        AttributeName: "LockID"
      ContributorInsightsSpecification:
        Enabled: false
      BillingMode: "PAY_PER_REQUEST"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      WarmThroughput:
        ReadUnitsPerSecond: 12000
        WriteUnitsPerSecond: 4000
      KeySchema:
      - KeyType: "HASH"
        AttributeName: "LockID"
      DeletionProtectionEnabled: false
      TableClass: "STANDARD"
      Tags:
      - Value: "state_lock"
        Key: "terraform_s3_backend"
      TimeToLiveSpecification:
        Enabled: false
